### ISSUE TITLE
Enter key causes 2 lines down, 1 line up

### ISSUE THREAD

**Issue by TjWheeler** [Alex-D/Trumbowyg#1005]
### Description
This issue was occurring in Chrome.  It seemed some of the semantic code aimed at IE was being executed.  Line 630 in the trumowyg.js currently was to blame.
```js
 var compositionEndIE = t.isIE ? e.type === 'compositionend' : true;
```
This seems malformed, as the True statement is an ignored comparison.
I have changed this to:
```js
var compositionEndIE = t.isIE && e.type === 'compositionend' ? true : false;
```
while this has fixed my issue, I'm not 100% sure what this is supposed to do, but thought I'd post in case its helpful.   Thanks for the great editor BTW.

**Comment by Alex-D** [comment]
```js
t.isIE ? e.type === 'compositionend' : true
```

means

```js
if (t.isIE) {
  return e.type === 'compositionend'
}

return true
```

> So:
> isIE === false => true

while

```js
t.isIE && e.type === 'compositionend' ? true : false
```

can be simplified into:

```js
return t.isIE && e.type === 'compositionend'
```

> So:
> isIE === false => false

So it not seams to be a mistake, you just disabled the code in all non-IE browsers ^^

----------

But the bug seams caused by running `semanticCode` with `full` flag set to `true` on enter... so your solution is not a solution, but maybe we just should not run this?

In semantic way, you should not have empty paragraphs, so double enter is a non-sense. Idk if I should allow this or not.

**Comment by TjWheeler** [comment]
Yes I see you are correct.  Essentially I disabled it in my scenario which did fix my issue but I probably could have set symantic:false in the options instead.
