### ISSUE TITLE
My love hate relationship with your control

### ISSUE THREAD

**Issue by jmichaelbrown** [Alex-D/Trumbowyg#1021]
I've implemented this control in a major app developed for the company I work for and now I am implementing it another project that requires COMPLETE control over html formatting.  I have toyed around with your semantic option off, I've included a list of tags to avoid and still your control does strange things to html.  I guess I am just having a hard time understanding why you ever thought it was a good idea to reformat html in the first place, what use case could this possibly be a benefit to?  The only way I can get this to work is to modify your source code and strip all of that out which I have done successfully but I loose the ability to preview and that's where I stopped wasting my time with it.

So with all of that said, is there a way to use your control so that it does not mess with html at all, I mean no changes at all?

**Comment by Alex-D** [comment]
I'm not sure which part of the code is annoying to you. Can you share me the removed function/code?

If you switch off the `semantic` option, Trumbowyg does not edit the HTML. It just use the browser's contenteditable API, which can be different between browsers (that's why I try to standardize them by changing some HTML tags to another).

Maybe you expect too many for an editor with small size as main goal?

Tell me more, maybe I will can help you.
