### ISSUE TITLE
Placeholder behavior

### ISSUE THREAD

**Issue by Cherinho** [Alex-D/Trumbowyg#1039]
Behavior of placeholder isn't correct right now. Placeholder disappearing after pur focus on the redactor element, but default behavior for any default inputs disappearing after put first symbol in input, not after focus

**Comment by Alex-D** [comment]
Feel free to improve the CSS which is responsible of this feature:

https://github.com/Alex-D/Trumbowyg/blob/80d3aa7cad6f1d50e7c1126d8fc478b5457185d8/src/ui/sass/trumbowyg.scss#L131

I don't think I will fix that in v2. I keep that in mind for v3.

Thank you for your feedback, I keep a eye on Pull Requests, if you make a little fix I will be more than happy to merge it :)

**Comment by deekoulos** [comment]
Hey Guys,

the issue is that if you click in to the editor it places <p><br></p> instantly. So the textarea is not "empty" anymore. This is why the css is not replacing the placeholder. I fixed this by adding the following code in to the trumbowyg.js, where the blur event is defined (line 650 v.2.21.0):

```
.on('focus blur', function (e) {
                    if (e.type === 'blur') {
                        if (e.currentTarget.innerHTML == "<p><br></p>") {
                            e.currentTarget.innerHTML = "";
                        }
```
Cheers
Dee

**Comment by reformed** [comment]
You can also utilize the `tbwblur` event:

    $('#editor').on('tbwblur', function() {
        if (!this.value) {
            $('#editor').trumbowyg("empty");
        }
    });
