### ISSUE TITLE
Add custom input to Code modal

### ISSUE THREAD

**Issue by weva-io** [Alex-D/Trumbowyg#1110]
Hi Alex,

I would like to add a custom checkbox to the _Code_ modal window that opens when the _Code syntax highlight_ button (`btns: ['highlight']`) is pressed + do some custom logic (for eg. in a callback function) based on the state of the custom checkbox when the _Confirm_ button of the modal is pressed. What would be the most efficient way to implement such functionality?

Thanks,

**Comment by mpryvkin** [comment]
I would suggest copying `/plugins/highlight` folder to `/plugins/highlight-mod`. Then you can tweak Highlight plug-in code `/plugins/highlight-mod/trumbowyg.highlight.js` and add the checkbox HTML code and callback JS code in `buildButtonDef` function. You would need to use modified plug-in instead of the original.

**Comment by weva-io** [comment]
This sounds like a good approach to me, thanks for the suggestion!

**Comment by Alex-D** [comment]
I approve: making your own plugin based on the existing one is the best way to do so :)
