### ISSUE TITLE
SVG icon for custom plugin

### ISSUE THREAD

**Issue by mapreal19** [Alex-D/Trumbowyg#1119]
I'm working on a custom plugin for inserting a page break, but is not quite ready for sharing with others. Is it possible to provide a custom SVG when creating the button definition?

Currently I'm just showing a text instead of a button.

```js
var pageBreakContent = '<div class="no-print" style="page-break-before: always;">{{Page Break}}</div>';

var btnPageBreak = {
    title: 'Page Break',
    text: 'Page Break',
    hasIcon: false,
    fn: function () {
        trumbowyg.execCmd('insertHTML', pageBreakContent)
    }
};
```

Regarding the page break feature, when I save the HTML in the server I add a style tag with the style `<style>.no-print { opacity:0;}</style>`  before printing the page, but I guess we can have a better solution without relying on the server. Just a hack that works for me now. 

Related: https://github.com/Alex-D/Trumbowyg/issues/814

**Comment by Alex-D** [comment]
Use `@media print { .no-print... }`

For the icon, check other plugins like giphy or upload, there is a folder with the SVG in it. It will embed at build time :)

**Comment by mapreal19** [comment]
I tried to follow the structure of other plugins:

![image](https://user-images.githubusercontent.com/3055997/82435012-fa64c700-9a93-11ea-8c59-3c68f30fbf98.png)

And import the plugin as stated in the docs:

```
<script src="https://cdnjs.cloudflare.com/ajax/libs/Trumbowyg/2.20.0/trumbowyg.min.js"></script>
<script src="/static/plugin/pagebreak/trumbowyg.pagebreak.js"></script>
```

The plugin works, is just the icon doesn't load. Do I need to be more specific somewhere? Or use a bundler like webpack? I'm using the CDN for now just for demo purposes.

**Comment by Alex-D** [comment]
You need to build Trumbowyg, all plugin icons are embed in the core :)

So you can't use CDN in this case.

**Comment by mapreal19** [comment]
@Alex-D I was able to build the library with Webpack, but adding a custom icon wasn't that easy. Maybe there should be a guide on how to use it with Webpack?

**Comment by lewiscollard** [comment]
Obviously, I am about three years late to the party here. But I'll leave my _less good_ solution to this for anyone in the future who is writing their own plugin.

If building your own custom Trumbowyg with Webpack sounds like effort, just bear in mind when Trumbowyg inserts its icon into your custom button, it points to an SVG symbol with the ID "trumbowyg-[yourpluginname]" in the document. Nobody said that it has to come from the sprite sheet that Trumbowyg injects! As long as it's somewhere in the document you'll be fine.

By which I mean, if you put something like this in the `init` of your plugin, replacing all instances of `myplugin` with your plugin name...

```javascript
if (!document.querySelector("#trumbowyg-myplugin")) {
    const iconWrap = document.createElementNS("http://www.w3.org/2000/svg", "svg");
    /*
    This class is only here to allow CSS to hide it, e.g. with

    .trumbowyg-myplugin-icons {
        display: none
    }
    */.

    iconWrap.classList.add("trumbowyg-myplugin-icons");
    // example icon by Remix Icon - https://remixicon.com/
    iconWrap.innerHTML = `
        <symbol id="trumbowyg-myplugin" viewBox="0 0 24 24">
          <path d="m20 13-5 1a15 15 0 0 1 3 5h2v-6zm-4 6c-2-5-7-8-12-8v8h12zM4 9c4 0 7 1 10 4a11 11 0 0 1 6-2V3h1l1 1v16a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1h3V1h2v4H4v4zm14-8v4h-8V3h6V1h2zm-1 9a2 2 0 1 1 0-3 2 2 0 0 1 0 3z"/>
        </symbol>
    `;
    document.body.appendChild(iconWrap)
}
```

...you can get whatever icon you like into your plugin's button, and it means your plugin can be distributed all by itself. No need to roll your own custom build! Because, as the kids say these days, ain't nobody got time for that.

@Alex-D if you think this solution is not too horrible to be documented I might do a PR for the docs.

**Comment by Alex-D** [comment]
That's the way I want to do it in version 3 ^^
So, I approve! :)
