### ISSUE TITLE
Font Case Buttons

### ISSUE THREAD

**Issue by justlester** [Alex-D/Trumbowyg#1135]
Hello! I kinda like the simplicity of this editor. 
I'm trying to create a custom button that makes letters to uppercase and lowercase.  
I'm new in making plugins like this. I read the documentation but I find hard to understand like how to get the highlighted text, enclosed it with "<span style='text-transform:uppercase'>< /span>" 
and then render it to the editor. 

A little help is appreciated, Thanks! :D

**Comment by Alex-D** [comment]
That's because it's not easy :/

Trumbowyg v2 is based on execCommand, so to edit something you need to call some execCommand thing, then do some manual transforms.

Check other plugins like font-size one:

https://github.com/Alex-D/Trumbowyg/blob/98be1fb0a253eb912a05e2beffa9c52a8b19ed32/plugins/fontsize/trumbowyg.fontsize.js#L217-L236
