### ISSUE TITLE
Responsive "Insert image" modal

### ISSUE THREAD

**Issue by dandv** [Alex-D/Trumbowyg#134]
In Chrome on Android, the *Insert image* modal is positioned such that field labels are out of the viewport:

![image](https://cloud.githubusercontent.com/assets/33569/7910954/a2ae5260-080d-11e5-8afa-d2dc2f29e5db.png)

I tried to zoom and pan but still couldn't see the full modal. This is easiest to reproduce if you try to insert an image with the caret in the first column.

**Comment by Alex-D** [comment]
The default style is not responsive yet.

**Comment by dandv** [comment]
Would be impressive to have a responsive demo page.

**Comment by kerwan** [comment]
I don't know if this might be useful but t i tried some adaptations for the image modal because i needed it to be responsive.

First using margin auto to center the modal and max-width allows the modal to shrink on smaller resolutions.
These are the rules i used : 

`.trumbowyg-modal {
    max-width: 90vw;
    width: 520px;
    height: 350px;
    z-index: 11;
    overflow: hidden;
    -webkit-backface-visibility: hidden;
    backface-visibility: hidden;
    position:absolute;
    left:0;
    right:0;
    margin-left:auto;
    margin-right:auto;
}

.trumbowyg-modal-box {
    backface-visibility: hidden;
    background-color: #fff;
    box-shadow: 0 2px 3px rgba(0, 0, 0, 0.2);
    font-size: 14px;
    padding-bottom: 45px;
    text-align: center;
    max-width: 90vw;
    width: 500px;
    z-index: 1;
    position:absolute;
    left:0;
    right:0;
    margin-left:auto;
    margin-right:auto;
}`

With little changes to the modal html you could use flexbox and media queries to achieve something a little more usable : 
if you put the "trumbowyg-input-infos" span before the input like this

`	<label>
			<span class="trumbowyg-input-infos">
				<span>URL</span>
			</span>
		<input type="text" value="" name="url">
	</label>`

you can use the following rules to get the same layout as before : 
`.trumbowyg-modal-box label {
	display: flex;
}

.trumbowyg-modal-box label .trumbowyg-input-infos {
	flex: 1;
	position: relative;
}

.trumbowyg-modal-box label input {
	position: relative;
}`

and then add one media query to stack label and input when the screen width gets too small

`@media screen and (max-width: 480px) {
	.trumbowyg-modal-box label {
		height: 54px;
		flex-direction: column; 
	}	
}`

Event without reversing the html markup it is still nice (except for the fact that the labels are on the right side instead of left)

Then again you might have to implement a fallback for older navigators who doesn't support flexboxes and that might be a pain.

**Comment by kerwan** [comment]
Here is what it looks like applying the rules, without reversing the input and form label.
On standard screen : 
![trumbowyg_large](https://cloud.githubusercontent.com/assets/3786171/13222006/480e61cc-d97e-11e5-855d-12e9b8d0280f.png)

And on small screen (width < 480 px)
![trumbowyg_small](https://cloud.githubusercontent.com/assets/3786171/13222061/809f9434-d97e-11e5-9beb-28845eb16bb4.png)

**Comment by Alex-D** [comment]
Done since v2.0.2
