### ISSUE TITLE
Insert image or link - JS error is thrown when page uses jQuery validation

### ISSUE THREAD

**Issue by abezulski** [Alex-D/Trumbowyg#20]
I am using your plugin (BTW, great work) on a page that also uses jQuery validation. Every time when I want to add link or image (pop-up appears), JS error is thrown "TypeError: c is undefined" and jQuery validation is referenced.

I have validated that erros are not thrown when page is not using jQuery validation.

Edit: still works, error does not prevent from further using.

**Comment by studiomado** [comment]
Hi Alex-D,
I have the same problem.
Another problem is that the link/image modals buttons is hidden or not exists.
If I disable jQuery Validation, your plugin it's work.

Can you fix it?

**Comment by Alex-D** [comment]
I need to take time to test this plugin. I think this is a configuration problème like disable validation plugin on Trumbowyg or something like that.

**Comment by Alex-D** [comment]
Don't understand how to fix that so I close it.

**Comment by RichardLindhout** [comment]
+1 on fixing this

**Comment by SquareBeard** [comment]
jQuery Validation fails because there is a nested form in some the modals of the editor.
This is related to the issue #126.

**Comment by jjbutera** [comment]
The implementation of the modal dialog for plugins really needs to be addressed and slightly redesigned so that a nested form is not created. The new form and overlay should be appended to the document and not the editor so you don't end up with nested forms (illegal syntax). This would also help disable all page interaction while the modal is open (or else why call it modal?). I also vote for giving the editor container an id to address other jQuery validate issues.
