### ISSUE TITLE
Entering new line only works the first time on IE

### ISSUE THREAD

**Issue by btecu** [Alex-D/Trumbowyg#305]
Using IE11 and Edge, if you press enter once, it works correctly adding a new line.
However, if you press enter again, it does not add a new line. Looking at the source, in IE it's adding `&nbsp;` for enter instead of `<br>` (in Chrome).

**Comment by Alex-D** [comment]
It's a content editable browser bug I think... Idk how to fix it :/

**Comment by Alex-D** [comment]
https://github.com/Alex-D/Trumbowyg/pull/308

**Comment by btecu** [comment]
That PR is closed, because you measure the code by the number of lines.

**Comment by Alex-D** [comment]
Wow, keep cool guy. I can keep this issue open. I just don't have the time to check all PR and edge cases. 

And yep, one of the project goal is to keep it small. So I count chars. All bugs could be fixed with a lot of code, but I want the smallest code for each patch. Let me the time to check that. I'm not a bot, I've got a life ;)
