### ISSUE TITLE
incompatibility with maxlength

### ISSUE THREAD

**Issue by woodgates** [Alex-D/Trumbowyg#316]
Before report an issue, be sure to put these informations. Thanks :)

### Informations
Hi.
I've implemented Trumbowyg and it's perfect for what I need. The problem I have is that when I set a value for maxlenght for the textarea the borser caluclates the length with the html, so the effective chars are much less than the real ones. 

**Browser + version**:
**OS**:
**Resolution**:

**Comment by Alex-D** [comment]
As you write: "the browser calculates the length". Not Trumbowyg.

If you want count only text length, you should do that via JS, maybe by listening [`tbwchange`](http://alex-d.github.io/Trumbowyg/documentation.html#events) event and do a `element.innerText || element.textContent;` on the editor element.

I don't want add this into Trumbowyg because it can be used to limit the length of a message for database VARCHAR for example.

**Comment by woodgates** [comment]
Hi Alex.
Thanks for your answer. Is it possible to set an Id for the "trumbowyg-editor"?

**Comment by Alex-D** [comment]
Nope :/ Because if you instanciate multiples editors, that's not good.

But there is already a class on it :)
