### ISSUE TITLE
[Proposal] Use font icons instead of SVG symbols

### ISSUE THREAD

**Issue by ramezrafla** [Alex-D/Trumbowyg#498]
It's now super easy to create fonts with https://icomoon.io/app/#/select with so many great free fonts (e.g. fontawesome and materialize). There is an easy workaround by specifying attributes to the buttons, but I suggest this for the long run.

@Alex-D if you are interested, I can generate the starting font for you and PR?

This will also make it easy to customize AND avoids the headache of building SVG symbols.

**Comment by Alex-D** [comment]
Nope.
I don't want use font-icons.
They are to ban, some arguments: https://css-tricks.com/icon-fonts-vs-svg/

**Comment by ramezrafla** [comment]
Ok, thanks. Will implement on our side.

I disagree with the site you linked (most issues are either edge cases or normal issues with fonts). For one, bootstrap and semantic use fontawesome, so we already have most icons built-in in most modern websites / apps (e.g. Materialize for Google apps). Not to mention that all text is font and looks great on most browsers.

In addition, adding or customizing svg symbols is an absolute pain (adding your own symbols requires some knowledge of SVG)

**Comment by Alex-D** [comment]
GitHub use SVG now.

I don't care about "adding your own symbols requires some knowledge of SVG". It's just a question of tooling. You know font tools. Trumbowyg has SVG tools.

You just have to add your SVG to icons folder and run `gulp build` which create the SVG sprite :)

Think about dyslexics which override all your fonts with a more readable one. He can't use the editor because icons are font. That's not OK. That's just bad accessibility.
