### ISSUE TITLE
strikethrough button does not stay selected after using it

### ISSUE THREAD

**Issue by Chinese1904** [Alex-D/Trumbowyg#521]
### Informations

**Browser + version**: Chrome 57 and Firefox 51 and 52
**OS**: MacOS 10.12.3
**Resolution**: Just 13inch Retina full screen

### How to reproduce the bug?

On http://alex-d.github.io/Trumbowyg/ you can try using the "strike through" button and you will realize it does not stay selected after using it.

**Comment by marlon-tucker** [comment]
May or may not be related, but I had a similar issue with bold and italic. 

Turns out I had the btnGrp-semantic button group selected while turning off semantic mode in the options. This prevented the tag detection from working correctly.

Using btnGrp-design instead fixed the issue. 

The documentation needs to be around this issue. Alternatively if you have a global setting for semantic mode, the buttons themselves should change their behavior depending on the mode of the control - instead of having different buttons.

**Comment by Alex-D** [comment]
> Turns out I had the btnGrp-semantic button group selected while turning off semantic mode in the options. 

You should not do that!

As you said, you need to use `btnGrp-design` which is used by default when you turns semantic off.

**Comment by Chinese1904** [comment]
Ok cool, I'll give it a try. 

@Alex-D FYI, on the demo on your homepage it needs to be fixed then as well. :-)

**Comment by Alex-D** [comment]
Oh? :-° OK. I will check that ASAP ^^'

**Comment by Alex-D** [comment]
Fixed since 2.8.0 I think :)
