### ISSUE TITLE
Toolbar buttons don't keep their highlighted state until the user types something

### ISSUE THREAD

**Issue by marlon-tucker** [Alex-D/Trumbowyg#525]
Browser: IE, Edge, Firefox, Chrome
OS: Windows 10,

When the user clicks a toolbar button, the code sends that command to the native browser editor. It looks like the browser doesn't immediately make the formatting change until the user types something - so as to not make DOM changes if the user clicks to another position I suspect.

The problem is, the highlight detection code assumes there are tags present in order to detect the format - and these are not yet present. 

Not totally sure on the best route to correct this behavior. Perhaps a flag on the button to say if the user clicked it which gets deleted if the user types or changes selection? 

From a user perspective, it is nice to know what the current formatting is going to be.

**Comment by Alex-D** [comment]
This feature is not availiable in Trumbowyg v2.

When you click, then you write, that does not works. I know and don't want to fix that because a lack of time.

If you write, then select text, then clic on a strong for example, text is wrapped into strong tags and the button correctly highlight that
