### ISSUE TITLE
Undo/Redo buttons not visible on Firefox

### ISSUE THREAD

**Issue by taalas** [Alex-D/Trumbowyg#564]
### Informations

**Browser + version**: Firefox latest
**OS**: Windows 10
**Resolution**: 1920x1080

The Undo/Redo buttons are not visible on Firefox, while they work perfectly on Chrome. This happens on my custom page using the plugin as well as the homepage demo. Is Undo/Redo not supported in Firefox? And if so, why?

**Comment by Alex-D** [comment]
Yep, undo/redo is only supported by Chrome. :/

**Comment by geonanorch** [comment]
Undo/Redo is a fairly important feature for a text editor. Trumbowyg would be even more popular if it were fully supported, I'm sure!

@Alex-D as a workaround for browsers having no native support: could the `tbwchange` event not be used to store successive states? That would be a very lightweight code-change, just some memory cost for the browser (but we are still talking Kb here).

If you are interested I can submit a pull request (also possible as plugin I guess, but less elegant because there is a possibility of clash with the default functionality).

**Comment by Alex-D** [comment]
You can try to make a PR yep, if it's too big, go to a plugin. If it's light, I'm OK to get it in core :)

**Comment by geonanorch** [comment]
just a note: I will work on this once the `resizimg` PR is through
