### ISSUE TITLE
delete uploaded image 

### ISSUE THREAD

**Issue by treesakul** [Alex-D/Trumbowyg#591]
I can't seem to find what is triggered when the image has been deleted. Is there anyway to know if the image is deleted? Since I upload images to the server using upload plugin, I need to delete the unused images.  Is there anything like on('image remove', function()....)

I have tried 'tbwchange', but it is triggered every time there're any changes.  I tried to keep changes between previous texts and current texts  and see if it's image tag. But there's a problem with keeping changes, undo, redo and performances.  So is there anyway to know if the image is deleted?

**Comment by Alex-D** [comment]
This kind of event is not supported by Trumbowyg, sorry. It's not easy to do.

**Comment by jung-hunsoo** [comment]
I'm looking for this feature too. And I thought how to implement it. Here is the quick process;

1) Create a `before edit` file list when Trumbowyg is loaded.
2) (... user edit...)
3) When the form is submitted, Trumbowyg makes the `after edit` file list.
4) Then Trumbowyg produces 'removed file list' by comparing the changes, so that the server can deal with the removed files.

But if there are more than one instance of Trumbowyg editor, then the trace lists need to be merged.

This feature will obviously reduce operation cost, and many users will cheer for Trumbowyg!

**Comment by spacedog4** [comment]
The only way around this would be list the uploaded images with the record, for example, an article, on the admin page, show the article fields like title and body with trumbowyg, and also show at the bottom all uploaded images, so the user can delete unused images.

You can also compare the server side image URLs with the content, if it isn't in the content, remove the image
