### ISSUE TITLE
Full path to SVG icons

### ISSUE THREAD

**Issue by thekrotek** [Alex-D/Trumbowyg#668]
I defined a path to SVG icons the way it's mentioned in documentation (with leading slash):

$.trumbowyg.svgPath = '/assets/my-custom-path/icons.svg';

And of course, at some point I hit the well known issue, when leading slash caused a problem on one of the sites. Removing the slash fixes the issue.

I know about this problem quite well and tend to define full path, when I load any kind of resources: CSS, JS, images, whatever. My question is simple: can I define full path for SVG icons as well? Like this:

$.trumbowyg.svgPath = 'http://mysite.com/assets/my-custom-path/icons.svg';

I'm pretty sure, I'm not the only one, who experienced this problem.

P.S.: Not sure, how to call this post - an issue, a suggestion or just a question, sorry :-)

**Comment by Alex-D** [comment]
Hum, if you are on the same domain, you can. If not, no, due to cross domain restrictions.

Code behind this is here: https://github.com/Alex-D/Trumbowyg/blob/develop/src/trumbowyg.js#L234

An HTTP GET request is sent through AJAX. Check your browser dev tools network tab to know if request is OK or not.

**Comment by thekrotek** [comment]
Yeah, it's for the same domain. Good, I'll change my code to the full path, because that stupid leading slash is always causing issues.
