### ISSUE TITLE
Set html to editor does not work

### ISSUE THREAD

**Issue by janfitz** [Alex-D/Trumbowyg#699]
### Informations
Setting content like below returns false. The same while getting html.
 `$('.trumbowyg').trumbowyg('html', htmlCode);`

**Browser version**: Chrome 63
**OS**: Linux Fedora

Thanks for help or fixing PR.

**Comment by Alex-D** [comment]
Last version of Trumbowyg? Can I have a sample code of a failing situation?

**Comment by janfitz** [comment]
Yeah, the last version. 

Here is code with trumbowyg init:
```
$('.trumbowyg').trumbowyg({
  lang: 'cs'
});

// Get code
var hiddenCode = $('#hiddenCode').val();
$('.trumbowyg').trumbowyg('html', hiddenCode);
```

Here is the html page with textarea>
```
<!-- Trumbowyg wysiwyg -->
<textarea class="trumbowyg"></textarea>
```

The getcode section extract content of hidden input where is some html code.

**Comment by jimchild49** [comment]
I just discovered the editor, I was curious to test this, it doesn't work in firefox either, after that I thought maybe I can put the html directly in the textarea, but it does show a contenteditable with toolbar inside another one ( 2 nested toolbars )

**Comment by Alex-D** [comment]
1/ You should not use an hidden input to do that. You should directly put the HTML into the textarea which is a form input.

2/ I've tested that: 

```javascript
$('textarea').trumbowyg()
$('textarea').trumbowyg('html', '<span class="toto">Some HTML</span>')
```

```html
<textarea></textarea>
```

Which is actually working in Chrome (and Opera), Firefox, Edge, IE11.

Test by yourself: https://jsfiddle.net/waa7jwdh/

----------

@jimchild49 You are in the wrong place since you are posting in an issue about a "bug" on 'html' API in Chrome :/ The code works in Firefox, as you can see above, so I did not understand your point. Without code sample, I can't help you. If you want more info/exchange, feel free to open another issue :)

**Comment by janfitz** [comment]
@Alex-D 

Thank you for your comment. After that i discovered that is works also with hidden input. I just have to use textarea identified by `id` not `class`. Probably it was the problem.

Good way:
```
$('#textarea').trumbowyg()
```
Bad way:
```
$('.textarea').trumbowyg()
```

**Comment by Alex-D** [comment]
Ah, yep, that's it! :)
