### ISSUE TITLE
using trumbowyg with existing fontawesome or glyphicons icons

### ISSUE THREAD

**Issue by dohomi** [Alex-D/Trumbowyg#70]
Hi,

do you plan an option to use existing glyphicons or / and fontawesome icons? Would be a nice option if a project has already the icon set included, it would generalise the icons and strip down the included source.

Cheers

**Comment by istrau3** [comment]
@Alex-D Can you expand on how to do this?

**Comment by Alex-D** [comment]
Since v2 : http://alex-d.github.io/Trumbowyg/documentation.html#svg-icons

You need to switch off SVG included feature by setting `svgPath` to `false`. Then, you can add your custom CSS based on button class. Each button has a class that follow this format:

`[prefix]-[buttonFunction]-button`
example: `trumbowyg-strong-button`

Go to your CSS and do what you want on this base :)

**Comment by TonyVlcek** [comment]
I have created a Gist which makes the buttons use FontAwesome icons: https://gist.github.com/TonyVlcek/0de8cbb185b6cfd10b9333828615d469

**Comment by renelc** [comment]
Example creating a button using fontawesome 4.7, to know wich code use on content, take a look into font-awesome.css and look for the icon you want

.trumbowyg-alert-button svg{
	display: none
}
.trumbowyg-alert-button:after {
	font-family: FontAwesome;
	content: "\f130";
}
