### ISSUE TITLE
disable svg buttons just for a plugin

### ISSUE THREAD

**Issue by Nazkter** [Alex-D/Trumbowyg#724]
I'm working on a plugin and I want it to have a font awesome icon. I already know that setting "svgPath: false" will disable SVG to all icons, but I need to disable it just for my plugin. Is there a way to achieve this?

**Comment by forelabs** [comment]
I have done it via this solution:

```
                    var btnDef = {
                        title: t.lang['yourPlugin'],
                        text: '<i class="fa fa-image" style="margin-right: 11px;" />',
                        hasIcon: false,
                        fn: function () {
                        // ...
                       }
                   };
```

**Comment by Nazkter** [comment]
oh! that is a good trick, I will try it but it does not feel like the correct way to do it. Is it the only way to do it?. Thanks for the help.

**Comment by forelabs** [comment]
The other - harder - way which comes up in my mind is to fork this project, convert font awesome icon you want to use to svg, add it to your plugin (use correct folder structure) and when building the dist, the bundled svg should include your new icon. If it is named same as the plugin, it should be automatically detected.

Because fa icons are fake content before text elements, it kinda makes sense to have them within the "text" part, because that is what an fa icon is. I think it is good enough for a simple own custom plugin.
But if you want to share your plugin with the rest, you should go with the "harder" solution.

**Comment by Nazkter** [comment]
thanks a lot! that clarifies some wrong thoughts that I have about how the SVG images for plugins works.

**Comment by Nazkter** [comment]
An additional comment: Font Awesome 5 comes with all icons in SVG in a folder.

**Comment by Alex-D** [comment]
You don't need to fork the project.

You can just change the `prefix` parameter and use your custom CSS and custom SVG.
