### ISSUE TITLE
Paste without formatting

### ISSUE THREAD

**Issue by talktoanil** [Alex-D/Trumbowyg#73]
Hello

We like this WYSIWYG editor and it lacks only 2 options. 

1. Paste without formatting
2. Remove formatting button in toolbar

Can you add these so that we can actually use it ? We need this feature as a lot of our users are going to copy-paste stuff in this editor from word files / web but we need to save it as text without formatting.

**Comment by Alex-D** [comment]
I've implemented the first point [here](https://github.com/Alex-D/Trumbowyg/blob/5809e0c3a0f0f0634c824351e292d23b96dd5f34/src/trumbowyg.js#L406);

And the second at the same lines :)

Soon in a release.

**Comment by viion** [comment]
:+1: Thanks for this! Works a charm =)

**Comment by viion** [comment]
Is this in release stage yet? I am using your editor for "Support Ticket" system (because its mega light), but as users post errors or messages from various web services, a lot of it becomes unreadable :(

I tried to use the version from git, but custom configs wouldnt work then, it was ignoring any parameter i included.

**Comment by Alex-D** [comment]
Hum... i don't have release the v2, but if you build from master it should be works.

Open a new issue for that.

**Comment by Alex-D** [comment]
I've just released the [`v2.0.0-beta.0`](https://github.com/Alex-D/Trumbowyg/releases/tag/2.0.0-beta.0) if you want check that the bug is correctly fixed.

Thanks!

**Comment by viion** [comment]
:+1: woo! I will check out tomorrow on my site and see if it is fine, if any problems I will create a new issue.
