### ISSUE TITLE
Javascript injection. Not a bug, more like a question.

### ISSUE THREAD

**Issue by s33kers** [Alex-D/Trumbowyg#732]
Is there any property or plugin which will exclude `<script>..</script>` and smth like `<p onclick="alert('injection')">BOOM</p>` added through "Insert code"? Cannot find anything in docs. for example flora editor has option htmlExecuteScripts

**Comment by forelabs** [comment]
As far as I know this is not present, but I am only a new plugin developer so maybe I miss something.
But even if you have this you should definitly check it once more on server side, because you can modify the data and send it to your server and when there is no validation, someone can still inject code.

**Comment by Alex-D** [comment]
You should clean that server side.

It's not to the front-end to do that.
