### ISSUE TITLE
Some errors

### ISSUE THREAD

**Issue by PaykomanVll** [Alex-D/Trumbowyg#823]
### Informations
**Browser version**: Chrome 67+
**OS**: win 10 Desktop
**Screen resolution**: 1920*1080

### Bugs
- Text-stroke can not be removed (click to stroke again and remove format, both work not)
- Superscript can only removed over remove-format (click again the super-button work not)
- Focus after a <hr> if it the last content work not, new text or elements wil put before the hr
- I think you have selction-problems, I have this content:
```<p>Hallo Welt, <del>das</del> ist die Hölle</p><p><hr></p><h2>foo</h2><p>baar</p><br>```
i make an double click on 'foo' and change to h1 (all fine) then change to h2 all before h2 and its self will now changed to h2. By more as one action without unselect or select again the text will format more as the selectet area.

### Missed feature
Dont use inline-css (respect CSP), better is build an option so that we can create a class list that will be used instead of css-commands. So we can allow only the pure HTML-Tag + the attribute class

### For me
I need the text align functions without add-style, can you help me for add a class instead style?

Best regards,
Paykoman

**Comment by Alex-D** [comment]
I know the editor is not perfect, but it is old also and is based on content editable. All bugs you point here are from the browser implementation of content editable.

Since the main goal of this editor is to keep it simple and light, I will not add tons of options.

For the align functions, try to redefine buttons with forceCSS to false: 
https://github.com/Alex-D/Trumbowyg/blob/develop/src/trumbowyg.js#L348-L363

Trumbowyg does not allows to add class. You can maybe do this via a plugin, check the docs to know how to create one.
