### ISSUE TITLE
Heading automatically get a <span> tag if the paragraph above them is copied in.

### ISSUE THREAD

**Issue by LightMode** [Alex-D/Trumbowyg#866]
### Informations

**Browser version**: Chrome Version 70.0.3538.67
**OS**: Windows 10
**Screen resolution**: 1400 x 900

### How to reproduce the bug?

1. Go to https://alex-d.github.io/Trumbowyg/
2. Delete everything in the editor.
3. Paste a paragraph from somewhere.
4. Press Enter and select and heading and put in a heading
5. Check the HTML, You will see that the heading tag actually has a span tag that has the heading text.

The problem that this creates is that the span tag has inline style that puts the font size at 14px. If I try to style the heading tag, it doesn't let me because the inline styles have more preference.

Sorry for bad english.

**Comment by Alex-D** [comment]
Maybe you should use the [remoformatPasted option](https://alex-d.github.io/Trumbowyg/documentation/#remove-format-pasted).

I can't reproduce it if I paste with Ctrl+Shift+V which ignore format. So I think it's due to HTML copy instead of text copy which can be resolve with the mentionned option :)
