### ISSUE TITLE
Custom button - $(this) editor?

### ISSUE THREAD

**Issue by albowler** [Alex-D/Trumbowyg#868]
Using the custom button example, is it possible to get **$(this)** of the editor when a custom button is clicked?

```
$('.trumbowyg').trumbowyg({
    btnsDef: {
        alert: {
            fn: function() {
                console.log($(this).trumbowyg('html'));
            },
            ico: 'blockquote'
        }
    },
    btns: [
        ['alert']
    ]
});
```

**Comment by Alex-D** [comment]
Hey, you should make a plugin and then use it.

https://alex-d.github.io/Trumbowyg/documentation/plugins/#create-your-own

**Comment by dearsina** [comment]
Sorry to jump on a closed thread, but so what's the point of the custom button function if we cannot reference anything other than the button name? Or has a way been developed subsequent to this question being posed?

**Comment by Alex-D** [comment]
It's an internal API exposed for those who want a simple button that do something external to the editor :)

**Comment by dearsina** [comment]
Thanks for the response. After I wrote my question, I managed to work the custom button feature to do what I wanted it to do, without having to piece together a plug-in (because frankly that seemed like a lot of work!).

I realised that I can feed the button parameters using the param key (the documentation isn't clear on this btw), so I just fed it the Trumbowyg ID (so that the button function could alter the text) and whatever else I needed. That did the trick.

Your system is a lot better slash easier to use than both Quill and Redactor. Thanks for your work.
