### ISSUE TITLE
Inserting Image from Clipboard will lag the editor / HTML Encoding

### ISSUE THREAD

**Issue by fuxifex** [Alex-D/Trumbowyg#891]
When inserting an image from Clipboard (eg. from the Windows snipping tool), the editor will start lagging, which means, when entering text, it will take several seconds until it appears.
I think this behaviour is normal, as the image will be Base64 encoded which causes a lot of data inside the editor. I think the only solution is uploading the image first (eg. to a temp-location) then only inserting and <img> tag.

2nd issue: when using .trumbowyg('html'), it would be nice if there was an option to receive html-encoded data for using in an AJAX-post for saving.

**Comment by Alex-D** [comment]
Yep, I cannot do anything better with base64. Feel free to make a Pull Request with a mix of Paste image and Upload plugins ^^

I will not manage HTML transformation like this in Trumbowyg since I want to keep the core light. Also, I did not understand what is wrong with AJAX using HTML as text? If you want sanitize, you must do it server-side, not client-side.

I close this to keep issues clean, feel free to comment :)
