### ISSUE TITLE
Many instances become render-blocking

### ISSUE THREAD

**Issue by nimr0dwastaken** [Alex-D/Trumbowyg#893]
**Hi Alex**
Love trumbowyg, in fact so much that i use it multiple times on several pages 😄 
But that leads the plugin fetching the icons.svg multiple times, once per textarea, which becomes a render-blocking problem.

as you can see:
![iconloads](https://user-images.githubusercontent.com/41329362/49586971-f8bc4780-f962-11e8-8d3b-4406c7fcf67d.JPG)

I'm Sure there's some clever way around this, or if not, is it something that could be fixed somehow?

Thanks in advance.

Edit: 
this is my call:
```js
    $('textarea').trumbowyg({
        btns: [
            ['viewHTML'],
            ['undo', 'redo'],
            ['formatting'],
            ['strong', 'em', 'del'],
            ['link'],
            ['justifyLeft', 'justifyCenter', 'justifyRight', 'justifyFull'],
            ['unorderedList', 'orderedList'],
            ['horizontalRule'],
            ['removeformat'],
            ['fullscreen']
        ]
    });
```

**Comment by Alex-D** [comment]
Hey!

Check out the "Use SVG icons without XHR" section here: https://alex-d.github.io/Trumbowyg/documentation/#svg-icons

I think it's the right way for you.

Another way if you want to keep the AJAX thing, is to make the AJAX call yourself once, insert the SVG in your HTML (like Trumbowyg does), then run your code. When the `#trumbowyg-icons` is in the HTML, Trumbowyg skip the AJAX call since icons are already available.

But I keep that in mind, there is some optimisation to do.
