### ISSUE TITLE
Attach external css file to the editor

### ISSUE THREAD

**Issue by callkalpa** [Alex-D/Trumbowyg#940]
This is a question, not a bug.

What I am trying to achieve is as follows,
* I have a set of styles defined in a css file.
* I need to have a set of custom buttons defined in the tool bar to apply each style (defined in css) to the selected text.

Is there a way to attach an external css just for the content of the editor? Or any other way to achieve the requirement?

**Comment by Alex-D** [comment]
> Is there a way to attach an external css just for the content of the editor?

There is no easy way to do so in the current HTML/CSS status:
- style scoped attribute is now removed/not supported
- Shadow DOM is not supported by every browsers

VusJS do this like that: https://vue-loader.vuejs.org/guide/scoped-css.html

Or you need to port your CSS to be `style`-ready and inject directly in style attribut when you wrap the selected text.

**Comment by lewiscollard** [comment]
Four years later, the situation has changed a lot, and shadow DOM is now [supported](https://caniuse.com/shadowdomv1) by 96% of browsers - basically, everything except either old and/or very bad & dead browsers. (By contrast, `querySelectorAll` is [just over 1% higher](https://caniuse.com/?search=queryselectorall). I think we're OK to use it now.) 

My situation is that I am using Trumbowyg in [Django's admin](https://docs.djangoproject.com/en/dev/ref/contrib/admin/). The Django admin has a lot of too-general CSS with high specificity which, even when combined with Trumbowyg's `resetCss` option, is requiring an increasing pile of similarly-overly-specific CSS to not look like nonsense. (To be clear, this is not Trumbowyg's fault at all.)

In this use case, I definitely don't want Trumbowyg's text to look anything like the document it is embedded in. Even browser defaults would be better, but better than that would be injecting a completely different stylesheet that makes Trumbowyg's text look like it does on the front end of the site, just as the OP did back when this issue was opened.

All of which is to say: would you accept a PR to add _optional_ shadow-DOM-with-custom-stylesheet support which would enable this use case? I am happy to try to write this because I _think_ this could actually be straightforward.
