### ISSUE TITLE
Svg icons didn't display in Safari

### ISSUE THREAD

**Issue by f3l1x** [Alex-D/Trumbowyg#954]
The svg icons didn't show up at Safari, but only since 2.15.x. It works in 2.14.0.

### Description
  - OS: Mac
  - Browser + version: Safari 12.0.2

### How to reproduce?

- Install trumbowyg 2.15.x

![image](https://user-images.githubusercontent.com/538058/55946208-8fb84980-5c4c-11e9-910f-8377d8fa87bc.png)

### Misc

It works with version 2.14.0.

**Comment by Alex-D** [comment]
Does it works here?
https://alex-d.github.io/Trumbowyg/

I did not have macOS, so no Safari to test on my own :/

**Comment by f3l1x** [comment]
Yes, it works on that page.

**Comment by Alex-D** [comment]
So. It seems to be an issue on your side ^^'

Any error message in console or network?

**Comment by f3l1x** [comment]
Well, you're right. I don't know where problem is, but it looks like. Thanks anyway. Have a nice day ;-)

**Comment by aromka** [comment]
Got the same issue. Only happens when going to the page from another route (angularjs), when doing full page refresh it works (that's why it also works here - https://alex-d.github.io/Trumbowyg/) - it also seems like the location its looking for svg is incorrect - is there a setting for it or something?

i.e. this is coming from a different page:

<img width="869" alt="coming-from-other-route" src="https://user-images.githubusercontent.com/2651029/59889282-adff9b80-9399-11e9-808c-ed0347c036ad.png">

if I refresh the page then it works fine:

<img width="842" alt="refreshing-the-page" src="https://user-images.githubusercontent.com/2651029/59889332-dab3b300-9399-11e9-894a-8b5aa7bca120.png">

div with SVG is loaded the same in both cases:

<img width="543" alt="icons-properly-loaded" src="https://user-images.githubusercontent.com/2651029/59889302-bbb52100-9399-11e9-8cd0-e8b8bede4142.png">

**Comment by aromka** [comment]
it looks like the problem happens on line 231:
`t.svgPath = !!t.doc.querySelector('base') ? window.location.href.split('#')[0] : '';`

setting it to empty string fixes the problem:
`t.svgPath = '';`

is there a reason why you path is changing the path when "base='/'" to current location even when svgPath is defined in config?

**Comment by Alex-D** [comment]
It must be a fix for other browsers, IE I think.

Must be fixed in v3
