### ISSUE TITLE
In IE, Mention is not working, no errors in console. Please need your help highly

### ISSUE THREAD

**Issue by mansres** [Alex-D/Trumbowyg#973]
https://github.com/Alex-D/Trumbowyg/tree/develop/plugins/mention

Any way this mention plugin is not working in IE 11 browser.
Even I tried your demos in IE.

 Please help me to fix this.

**Comment by Globulopolis** [comment]
Please, provide a bit more information. Errors in console or code which you use to load.

**Comment by Alex-D** [comment]
I think it's due to insertHTML execCommand which is not supported?

**Comment by Globulopolis** [comment]
>  think it's due to insertHTML execCommand which is not supported?

Does it mean that all plugins which using `insertHTML` will not work anymore?
https://github.com/Alex-D/Trumbowyg/blob/develop/plugins/highlight/trumbowyg.highlight.js#L46
https://github.com/Alex-D/Trumbowyg/blob/develop/plugins/noembed/trumbowyg.noembed.js#L91
https://github.com/Alex-D/Trumbowyg/blob/develop/plugins/pasteembed/trumbowyg.pasteembed.js#L85
https://github.com/Alex-D/Trumbowyg/blob/develop/plugins/preformatted/trumbowyg.preformatted.js#L66

**Comment by Alex-D** [comment]
anymore => never worked in IE

Yep, I think. I've said that a lot of times, but since people seams to not really care about IE, I've merged a log of plugins.

Maybe it could be cool to implement `isSupported` in all of that plugins.

Also, since v3 is on his way, I do not think to fix that in v2. Moreover, the best move should be to put a polyfill in core, but the core does not use insertHTML since it's not working in IE, so it must be a copy/paste of the polyfill in each plugin.

**Comment by Globulopolis** [comment]
Ok, I see two ways. Wait for v3 and when update the code or drop support for old IE. :)

**Comment by Alex-D** [comment]
Seems all of this can be fixed by the PR #763

**Comment by sbrl** [comment]
Just found this issue browsing GitHub. I'd just remind everyone that IE is now no longer supported by Microsoft. I'd recommend Edge instead if you like Microsoft web browsers, which is the spiritual successor to Internet Explorer.

**Comment by Alex-D** [comment]
IE is no longer supported, so I am closing this issue.
